import React, { useState, useEffect } from 'react';
import { AlertTriangle, CheckCircle, Filter, Search, ArrowRight } from 'lucide-react';
import { SecurityAlert } from '../types/threat';

export const AlertsPage: React.FC<{ onInspectTarget: (target: string) => void }> = ({ onInspectTarget }) => {
  const [alerts, setAlerts] = useState<SecurityAlert[]>([]);
  const [filter, setFilter] = useState<'ALL' | 'OPEN' | 'RESOLVED'>('OPEN');

  const fetchAlerts = async () => {
    try {
      const res = await fetch('/api/alerts');
      if (res.ok) setAlerts(await res.json());
    } catch (e) {
      console.error(e);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, []);

  const handleResolve = async (id: string) => {
    try {
      await fetch(`/api/alerts/${id}/resolve`, { method: 'PATCH' });
      await fetchAlerts();
    } catch (e) {
      console.error(e);
    }
  };

  const filtered = alerts.filter(a => {
    if (filter === 'OPEN') return !a.resolved;
    if (filter === 'RESOLVED') return a.resolved;
    return true;
  });

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <div className="flex items-center space-x-2">
            <h1 className="text-xl font-bold text-white tracking-wide">Security Incident & Alert Queue</h1>
            <span className="px-2 py-0.5 text-[10px] font-mono bg-red-950 text-red-400 border border-red-800 rounded">
              INCIDENT RESPONSE
            </span>
          </div>
          <p className="text-xs text-gray-400 mt-1">
            Automated notifications generated by high-risk detections, certificate expiries, and rogue redirects.
          </p>
        </div>

        <div className="flex space-x-2 font-mono text-xs">
          <button
            onClick={() => setFilter('OPEN')}
            className={`px-3 py-1.5 rounded-lg border ${
              filter === 'OPEN' ? 'bg-red-950/80 border-red-800 text-red-400' : 'bg-gray-900 border-gray-800 text-gray-400'
            }`}
          >
            OPEN ({alerts.filter(a => !a.resolved).length})
          </button>
          <button
            onClick={() => setFilter('RESOLVED')}
            className={`px-3 py-1.5 rounded-lg border ${
              filter === 'RESOLVED' ? 'bg-emerald-950/80 border-emerald-800 text-emerald-400' : 'bg-gray-900 border-gray-800 text-gray-400'
            }`}
          >
            RESOLVED ({alerts.filter(a => a.resolved).length})
          </button>
          <button
            onClick={() => setFilter('ALL')}
            className={`px-3 py-1.5 rounded-lg border ${
              filter === 'ALL' ? 'bg-gray-800 border-gray-700 text-white' : 'bg-gray-900 border-gray-800 text-gray-400'
            }`}
          >
            ALL ({alerts.length})
          </button>
        </div>
      </div>

      {filtered.length > 0 ? (
        <div className="space-y-3 font-mono">
          {filtered.map((alt) => (
            <div
              key={alt.id}
              className={`p-4 rounded-xl border flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 ${
                alt.resolved
                  ? 'bg-[#0d141f]/40 border-gray-800/80 opacity-70'
                  : 'bg-[#140d11] border-red-900/60 shadow-lg shadow-black/40'
              }`}
            >
              <div className="space-y-1">
                <div className="flex items-center space-x-2.5">
                  <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                    alt.severity === 'CRITICAL' ? 'bg-red-950 text-red-400 border border-red-800' : 'bg-amber-950 text-amber-400 border border-amber-800'
                  }`}>
                    {alt.severity}
                  </span>
                  <span className="text-xs font-bold text-white">{alt.title}</span>
                  <span className="text-[10px] text-gray-500">
                    {new Date(alt.createdAt).toLocaleString()}
                  </span>
                </div>
                <div className="text-xs text-gray-300 font-sans">{alt.description}</div>
                <div className="text-[11px] text-gray-500">Target Indicator: {alt.target}</div>
              </div>

              <div className="flex items-center space-x-2 shrink-0">
                <button
                  onClick={() => onInspectTarget(alt.target)}
                  className="px-3 py-1.5 rounded bg-gray-800 hover:bg-gray-700 text-xs text-gray-200 flex items-center space-x-1"
                >
                  <span>Investigate</span>
                  <ArrowRight size={12} />
                </button>
                {!alt.resolved && (
                  <button
                    onClick={() => handleResolve(alt.id)}
                    className="px-3 py-1.5 rounded bg-emerald-950 text-emerald-400 border border-emerald-800 hover:bg-emerald-900 text-xs flex items-center space-x-1"
                  >
                    <CheckCircle size={12} />
                    <span>Resolve Alert</span>
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="p-16 text-center rounded-xl bg-[#0e1422]/60 border border-gray-800">
          <CheckCircle size={40} className="mx-auto mb-3 opacity-30 text-emerald-500" />
          <h3 className="text-sm font-semibold text-gray-300">Alert Queue Clean</h3>
          <p className="text-xs text-gray-500 mt-1 max-w-sm mx-auto">
            No incidents matching your filter criteria are currently flagged in the system.
          </p>
        </div>
      )}
    </div>
  );
};
